### PR TITLE
RecyclerView

### PR DESCRIPTION
**Pull request by HeaDBanGer84**
Hi,
this should be the patches you want. Some things i just commented out...feel free to change the layout of the List. I would prefer the Cardviews anyway ;-)
Screenshot:
bildschirmfoto von 2016-01-05 10-20-30

### CODE REVIEW

**Comment by HeaDBanGer84** [comment]
No conflicts, ready to merge

**Comment by stefan-niedermann** [comment]
thanks, will merge on saturday.

**Comment by HeaDBanGer84** [comment]
updatet Layout:
layout

**Comment by stefan-niedermann** [comment]
@HeaDBanGer84 since list layout is the way we will go, i would remove all card layout references - it's currently only dead code and bloats the source. i will only adapt the recycler view and remove the flags (```public final static boolean CARDLAYOUT=false;```).
I don't want you to spent too much time on unnecessairy things...

**Comment by stefan-niedermann** [comment]
So i did some cherry picking from your pull request in https://github.com/stefan-niedermann/OwnCloud-Notes/commit/c277dcae104c191560b774ef37805848ad04f8dc.
It currently still does not look perfect (the height of the icons seems to be strange).

Because its Work in Progress, i created a branch "RecyclerView".

Regards

**Comment by stefan-niedermann** [comment]
Recycler View branch has been merged to master branch.

**Pull request closed without merging**
