### PR TITLE
Fixing sychronization and concurrency issues

### LINKED ISSUE #76: Editing saves on every keypress. It hammers my connection.
It appears that the application tries to mimic the approach on the ownCloud web front end, which has no explicit save mechanism.

As far as I can see, for every keystroke the whole file is being sent to the server. If let us say the user is editing a largish note on low bandwidth, this becomes a bit of a problem. It also totally screws up my Activity feed.

Why not:
* Have an explicit save mechanism (e.g., an icon, menu option) so the user can choose when to save.
* Save automatically on leaving the note (going back to notes list, dismissing application)
* Save automatically after a period of inactivity. Let us say, if the user has not typed anything in the last *x* seconds.

The options above need not be mutually exclusive. Do note however that any automatic saves should have an undo option, to allow the user to recover from accidents (the web front end provides this via file versioning).

### LINKED ISSUE #104: don't autosave if the note isn't modified
Sometimes I like to copy the raw marckdown code and paste in other app. OCN thinks that I edited the note and save it showing it the first if the list when I didn't.

It would be nice an option to change the sort or cancel the automatic save in these situations.

### LINKED ISSUE #117: Notes created or edited in airplane mode are deleted when online
Steps to recreate:
1. Turn on airplane mode
2. Create or edit notes in the app. The notes appear last as duplicates to the original notes
3. Turn off airplane mode
4. Refresh app. Notes and edits are lost

owncloud server version: 9.0.2
notes version: 2.0.1
android ownCloud Notes: 0.8.1

### LINKED ISSUE #119: Show an error message if synchronization fails
I've tested the app (v0.8.1 from F-Droid on Cyanogen OS 13.0 / Android 6.0.1, German) with some ownCloud servers and it appears, that the app does not show any message, that informs about errors during login or synchronization (except if the server address is wrong).

I.e., no error is presented and it looks like everything is fine for the following cases:

* If I connect to a server with wrong user name and/or password
* If I connect to a server on which the ownCloud Notes app is not activated or even available (i.e. ownCloud 7)
* If I change or create a new note, there is no clue, if this note is synchronized successfully or not

Therefore, I suggest to show meaningful error messages if
* the login fails,
* synchronization is not successful

AND introduce a small icon at the right margin of each note in the ListView (main activity) which is shown if the corresponding note was not synchronized yet (e.g. since it is new or was changed). With this, you have a good overview if everything is fine and it does not bloat the app layout in the normal case (everything is sync'd).

### PR DESCRIPTION
**Pull request by korelstar**
This is the current state of my attempt to fix #117. It's not fully finished yet, but the majority of the work is done. Therefore, please have a look at this pull request and test it with all the test cases you can imagine. I will update the pull request continually.

#### Finished Tasks
- [x] **Database:** new column `REMOTE_ID` (fixes conflicts between parallel creation of different notes locally and remotely)
- [x] **DBStatus:** `LOCAL_CREATED` is not used anymore (distinction if Note is new or edited can be made with checking `REMOTE_ID=0`; fixes conflicts on synchronization and parallel local edits)
- [x] **Note:** model is split in to `DBNote` (representing the local DB entry of a note) and `OwnCloudNote` (representing the remote note, used by `NotesClient`).
- [x] **ItemAdapter/note item layout:** show icon for unsynchronized changes (simplifies debugging, includes all changes done in #121, closes #119)
- [x] **NoteSQLiteOpenHelper:** database upgrade (add the new column and adapts the data without flushing the database)
- [x] **NoteSQLiteOpenHelper:** add more constraints for database updates (fixes lost updates due to parallel changes of notes (from synchronization and user interface))
- [x] **NoteSQLiteOpenHelper:** `updateNoteAndSync()`: only make database changes, if the content really changed (fixes #104, at least the original intention of the author).
- [x] **NoteSQLiteOpenHelper:** remove recurrent code (improves code quality)
- [x] **NoteServerSyncHelper:** only update if network is connected (fixes lots of thrown exceptions)
- [x] **NoteServerSyncHelper:** schedule synchronization requests (if synchronization is active or network not connected; fixes missing push of *all* outstanding changes)
- [x] **NoteServerSyncHelper:** restructure the communication between synchronization task and user interface.
- [x] **NoteServerSyncHelper:** consolidate synchronization AsyncTasks into a single one (improves code quality)
- [x] **EditNoteActivity:** ensures, that auto-save is not called, if the previous auto-save is still running. In addition, start next auto-save not before a small delay has passed. (This could fix #76)

#### Other Issues I've Found (not covered by this pull request)
- There is no conflict resolution for the case that a Note is locally and remotely edited in parallel (e.g. during a longer time without network connection). Currently, local changes overwrite remote changed. We have to discuss what would be the desired behavior. See also #66.
- The `ItemAdapter` should use a `CursorAdapter` which is updated automatically if the backend data is changed.
- In order to save traffic during synchronization, `pullRemoteChanges()` could use the `exclude` parameter of the [Notes API](https://github.com/owncloud/notes/wiki/Notes-0.2) in a first step to check which notes changed without downloading unchanged notes. Only in the second step, the whole note content would be downloaded from the changed note. This could save traffic, however, it has to be investigated if the effort worth it (what is the typical/topmost number and size of notes?).

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
I think i have some free time at this weekend. I'll test this, merge this and if all is going well, i'll build a new version for F-Droid.

**Comment by stefan-niedermann** [comment]
looks good. shall i wait for the three open tasks or do prefer to merge now?

**Comment by korelstar** [comment]
I tested my branch again and I found an embarrassing bug. Unfortunately, I can't fix before Monday. So please wait a few days. I'll write a comment here when I'm finished.

**Comment by korelstar** [comment]
ready to merge :-)

**Comment by moshpirit** [comment]
\o/ wooohoo! Thanks a lot for the support!!

**Comment by stefan-niedermann** [comment]
@korelstar just let me say a huge **thank you** again - i just had time again to watch your code and it looks awesome.
I want to tag a new version for F-Droid since the current version 0.8.1 is buggy. One little thing i noticed: If you are doing a clean install of the app (or purge any data of it) and start it, you will get into the settings activity - that's fine, but it trys to sync and fails (and shows an error message).
I don't have a problem if it trys a sync on first start-up, but it should at least not display an error message.

**Comment by korelstar** [comment]
I will have a look at this issue and fix it as soon as possible, but I can't tell when, since I just changed my residence and I haven't access to my working station yet.

**Pull request merged**
