### PR TITLE
Replace ListView by a RecyclerView

### LINKED ISSUE #30: New note gets sorted all the way down in the list
When you create a new note from the app and go back to the list, it’s nowhere to be found. Then you scroll all the way to the bottom and se the »Updated recently« section all the way down. To make it appear up top you have to manually refresh.

Instead it should automatically be sorted up top as it has the newest date.

### PR DESCRIPTION
**Pull request by Kernald**
(Dot **not** merge yet, it's still WIP)

This PR will fix #30 and migrate from `ListView`s to `RecyclerView`s, allowing more flexibility. For now, I simply replaced the `ListView` in one activity (`NotesListViewActivity`). To do:
- [x] Fix note creation callback
- [x] Replace `ListView` by `RecyclerView` in `NotesListViewActivity`
- [ ] Replace `ListView` by `RecyclerView` in `SelectSingleNoteActivity`
- [ ] Implement back the sections pattern in the new `NoteAdapter` (replacing the `ItemAdapter`)
- [ ] Add some separators between items (handled automatically by `ListView`, to do manually with a `RecyclerView`)

The `NoteAdapter` uses a `SortedList` to store `Notes`, and is always sorted (here's the fix to #30, mainly a side-effect of switching to `RecyclerView` ;-))

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Hi @Kernald, do you have an idea, when this PR will be finished? I am trying to do as little changes as possible to avoid merge conflicts.

**Comment by Kernald** [comment]
Hi, sadly I don't have much time these days. I'll make it as soon as possible, but I can't give you any ETA. Just go ahead and make the changes you want, I'll handle the conflicts ;-)

**Comment by Kernald** [comment]
Hello,
I'm sorry to announce that, but I had some unexpected changes at work, I won't be able to work on this in a reasonable timeframe. Obviously, feel free to use the code I already wrote ;-) Good luck with your application, I'm looking forward to see it evolve.

**Comment by HeaDBanGer84** [comment]
I had the same idea and some time to spare over the hollydays but without having seen this.
The Results can found at https://github.com/HeaDBanGer84/OwnCloud-Notes.git Branch: materialDesign
It works so far, but still needs some testing I guess.

**Comment by stefan-niedermann** [comment]
Hi @HeaDBanGer84,

your contribution is very welcome! I have some questions, but we will discuss this in the [commit](https://github.com/HeaDBanGer84/OwnCloud-Notes/commit/8ca35c65ec87be79498c5d13568902b09ca654bc).
Could you please rebase, synchronize with my repository and resolve the merge conflicts?
If you are ready, please open a pull-request and then we can merge this in :)

Best regards

**Comment by stefan-niedermann** [comment]
I think this PR is outdated thanks hb84.

**Pull request closed without merging**
