### PR TITLE
Persistant notification for creating new notes

### PR DESCRIPTION
**Pull request by kas70**
Can be enabled with a checkbox preference.

I did this for myself because i needed a quick way for creating new notes. Maybe this is useful for you.
@stefan-niedermann

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Thank you for contribution @kas70 !
@jancborchardt your opinion please: Do you think this is a setting, that will be used wildly? I'm struggling with myself because even it is a great feature i am not sure if it should be built in.

**Comment by jancborchardt** [comment]
Hm, usually this would be solved with a widget, no? Isn’t hacking the notifications for that a bit non-standard?

I would definitely have it as a setting only instead of the default.

**Comment by kas70** [comment]
Persistent notifications are often used for providing access to quick actions. Further, i'm personally no friend of widgets, but that's a matter of taste.

**Comment by jancborchardt** [comment]
Ok, seems fine then as an off-by-default setting. :)

**Comment by stefan-niedermann** [comment]
Okay, i think i will merge it even if i feel a bit uncomfortable with it.
Don't get me wrong, i just don't want to create too much settings for user which only maybe 5 % will use. (Maybe we can think about adding some Tabs to the Settings Activity, or a "advanced options"-drop down so most user will only see the url & credentials stuff - if we get more options).

**Comment by jancborchardt** [comment]
@stefan-niedermann I totally agree, I’m also for less settings and stuff to maintain.

**Pull request merged**
